import { Section } from '@/types/galaxy';

export const sections: Section[] = [
  {
    id: 'intro',
    name: 'Intro',
    position: [0, 0, 0],
    cameraPosition: [2, 0, 18],
    planetColor: '#3b82f6',
    planetEmissive: '#1d4ed8',
    size: 3,
    hasRing: true,
  },
  /* {
    id: 'hero',
    name: 'Start',
    position: [0, 0, 0],
    cameraPosition: [0, 2, 12],
    planetColor: '#3b82f6',
    planetEmissive: '#1d4ed8',
    size: 3,
    hasRing: true,
  }, */
  /*   {
    id: 'hero-info',
    name: 'Vorstellung',
    position: [0, 0, 0],
    cameraPosition: [-2, 1, 10],
    planetColor: '#3b82f6',
    planetEmissive: '#1d4ed8',
    size: 3,
    hasRing: true,
  }, */
  {
    id: 'hero-orbit',
    name: 'Start Orbit',
    position: [0, 0, 0],
    cameraPosition: [5, 3, 8],
    planetColor: '#3b82f6',
    planetEmissive: '#1d4ed8',
    size: 3,
    hasRing: true,
  },
  {
    id: 'transition-skills',
    name: 'Auf zu Skills',
    position: [-12, 3, -20],
    cameraPosition: [-10, 5, -10],
    planetColor: '#06b6d4',
    planetEmissive: '#0891b2',
    size: 0,
    hasRing: false,
  },
  {
    id: 'skills-approach',
    name: 'Skills Annäherung',
    position: [-25, 5, -40],
    cameraPosition: [-35, 10, -28],
    planetColor: '#10b981',
    planetEmissive: '#059669',
    size: 4,
    hasRing: false,
  },
  {
    id: 'skills',
    name: 'Skills',
    position: [-25, 5, -40],
    cameraPosition: [-40, 8, -40],
    planetColor: '#10b981',
    planetEmissive: '#059669',
    size: 4,
    hasRing: false,
  },
  {
    id: 'skills-orbit',
    name: 'Skills Orbit',
    position: [-25, 5, -40],
    cameraPosition: [-38, 6, -52],
    planetColor: '#10b981',
    planetEmissive: '#059669',
    size: 4,
    hasRing: false,
  },
  {
    id: 'skills-close',
    name: 'Skills Nahaufnahme',
    position: [-25, 5, -40],
    cameraPosition: [-28, 5, -55],
    planetColor: '#10b981',
    planetEmissive: '#059669',
    size: 4,
    hasRing: false,
  },
  {
    id: 'transition-projects',
    name: 'Auf zu Projekten',
    position: [5, -2, -55],
    cameraPosition: [0, 0, -50],
    planetColor: '#6366f1',
    planetEmissive: '#4f46e5',
    size: 0,
    hasRing: false,
  },
  {
    id: 'project-1',
    name: 'KickCompare',
    position: [51, -8, -80],
    cameraPosition: [42, -6, -72],
    planetColor: '#8b5cf6',
    planetEmissive: '#7c3aed',
    size: 5,
    hasRing: true,
  },
  {
    id: 'project-2',
    name: 'Dartsync',
    position: [19, -8, -62],
    cameraPosition: [12, -4, -55],
    planetColor: '#8b5cf6',
    planetEmissive: '#7c3aed',
    size: 5,
    hasRing: true,
  },
  {
    id: 'projects-overview',
    name: 'Projekte Übersicht',
    position: [30, -8, -80],
    cameraPosition: [30, 5, -60],
    planetColor: '#8b5cf6',
    planetEmissive: '#7c3aed',
    size: 5,
    hasRing: true,
  },
  {
    id: 'transition-about',
    name: 'Auf zu Über Mich',
    position: [10, 2, -105],
    cameraPosition: [15, 5, -95],
    planetColor: '#ec4899',
    planetEmissive: '#db2777',
    size: 0,
    hasRing: false,
  },
  {
    id: 'about-approach',
    name: 'Über Mich Annäherung',
    position: [-15, 10, -130],
    cameraPosition: [-5, 15, -115],
    planetColor: '#f59e0b',
    planetEmissive: '#d97706',
    size: 3.5,
    hasRing: false,
  },
  {
    id: 'about',
    name: 'Über mich',
    position: [-15, 10, -130],
    cameraPosition: [-15, 13, -118],
    planetColor: '#f59e0b',
    planetEmissive: '#d97706',
    size: 3.5,
    hasRing: false,
  },
  {
    id: 'about-orbit',
    name: 'Über Mich Orbit',
    position: [-15, 10, -130],
    cameraPosition: [-22, 12, -125],
    planetColor: '#f59e0b',
    planetEmissive: '#d97706',
    size: 3.5,
    hasRing: false,
  },
  {
    id: 'finale',
    name: 'Finale',
    position: [-15, 10, -130],
    cameraPosition: [-10, 18, -140],
    planetColor: '#f59e0b',
    planetEmissive: '#d97706',
    size: 3.5,
    hasRing: false,
  },
];

export const mainSections = [
  {
    id: 'hero',
    name: 'Start',
    startIndex: 0,
    color: '#3b82f6',
    description: 'Willkommen in meiner Galaxie',
  },
  {
    id: 'skills',
    name: 'Skills',
    startIndex: 4,
    color: '#10b981',
    description: 'Meine Technologien',
  },
  {
    id: 'projects',
    name: 'Projekte',
    startIndex: 9,
    color: '#8b5cf6',
    description: 'Meine Arbeiten',
  },
  {
    id: 'about',
    name: 'Über mich',
    startIndex: 15,
    color: '#f59e0b',
    description: 'Mein Werdegang',
  },
];

export const navigationSections = [
  { id: 'hero', name: 'Start', sectionIndex: 1, color: '#3b82f6' },
  { id: 'skills', name: 'Skills', sectionIndex: 4, color: '#10b981' },
  { id: 'projects', name: 'Projekte', sectionIndex: 9, color: '#8b5cf6' },
  { id: 'about', name: 'Über mich', sectionIndex: 15, color: '#f59e0b' },
];
